homeassistant:
  name: Yggdresil
  latitude: !secret me_lat
  longitude: !secret me_long
  elevation: 430
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include configuration.d/customize.yaml

# password and certs
http:
  api_password: !secret hass_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key

# making my house a robot
automation: !include configuration.d/automation.yaml

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config/

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

device_tracker:
  - platform: locative

# Sensors
sensor: !include configuration.d/sensors.yaml

# Switches
switch: !include configuration.d/switch.yaml

# Security
camera: !include configuration.d/camera.yaml

# Media
media_player: !include configuration.d/media_player.yaml

# Groups (setting up display)
group: !include configuration.d/views.yaml

# Zones
zone: !include configuration.d/zone.yaml
