#  - alias: 'Dusk on'
#    trigger:
#      platform: sun
#      event: sunset
#      offset: "-00:25:00"
#    action:
#      service: switch.turn_on
#      entity_id: switch.the_sparkle 
#  - alias: 'auto off at bedtime'
#    trigger:
#      platform: time
#      after: "22:10:00"
#    action:
#      service: switch.turn_off
#      entity_id: switch.the_sparkle 
    trigger:
      platform: time
      after: "18:04:00"
    action:
      service: switch.turn_on
      entity_id: switch.bedroom_lamp
#  - alias: 'bedroom trickery off'
    trigger:
      platform: time
      after: "22:30:00"
#    action:
#      service: switch.turn_off
#      entity_id: switch.bedroom_lamp
